kumuluzee:
  name: rso-airline-recommendation
  version: 1.1.0
  env:
    name: dev
  server:
    base-url: http://localhost:8085
    http:
      port: 8085
  datasources:
  - jndi-name: jdbc/fri_airline
    connection-url: lala
    username: postgres
    password: pass
    max-pool-size: 20