apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
      - image: rsoairlines/fri-airlines-recommendation:0.0.1
        name: recommendation
        env:
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: gcloud
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        ports:
        - containerPort: 8085
          name: server
          protocol: TCP
